language: node_js
node_js:
    - "node"

before_install:
  - sudo apt-get update
  - npm update -g npm
  - npm install -g grunt-cli

install:
  - npm install
  - npm rebuild

cache:
  directories:
    - node_modules

script:
  - grunt audit
